---
repos:
  - repo: https://github.com/bazzasti/easy-imm
    rev: v1.50.0
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint

  - repo: https://github.com/bazzasti/easy-imm
    rev: v0.16.0
    hooks:
      - id: terraform-docs-system
        args: ['.']