---
#========================================
#   Global Settings
#========================================
global_settings:
  intersight_fqdn: intersight.com
  tags:
    - key: Module
      value: terraform-intersight-easy-imm
    - key: Version
      value: 3.1.5
